version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          command: npx update-browserslist-db@latest 
      - run:
          name: Build
          command: CI=false npm run build
      - run:
         name: Archive the artifact
         command: tar -czvf circle-ci-project.tar.gz dist/
      - persist_to_workspace:
          root: .
          paths:
            - circle-ci-project.tar.gz
                  
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://107.22.46.30:9000 \
              -Dsonar.token=$SONAR_TOKEN
              
  nexus:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /workspace
      - run:
          name: Upload artifact to Nexus
          command: |
            curl -v -u $NEXUS_USERNAME:$NEXUS_PASSWORD --upload-file /workspace/circle-ci-project.tar.gz \
            $NEXUS_URL/repository/$NEXUS_REPOSITORY/circle-ci-project.tar.gz 

workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      - nexus:
          requires:
            - build
            
