version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          command: npx update-browserslist-db@latest 
      - run:
          name: Build
          command: CI=false npm run build
         
      - run:
         name: Archive build artifacts
         command: |
           mkdir -p build/artifacts
           # Replace 'dist' with your actual build output directory
           cp -r build/static/js/* build/artifacts/
           cd build/artifacts
           zip -r ../artifact.zip .
           cd ../..
           echo "Contents of the build directory after zipping:"
           ls -l build
      - persist_to_workspace:
          root: .
          paths:
            - build/artifact.zip
      
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://107.22.46.30:9000 \
              -Dsonar.token=$SONAR_TOKEN
              
  nexus:
    executor: node-executor
    steps:
      - checkout
      - run:
         name: Verify artifact
         command: ls -l build/artifact.zip
      - run:
          name: Upload artifact to Nexus
          command: |
            curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD \
            --upload-file build/artifact.zip \
            $NEXUS_URL/repository/$NEXUS_REPOSITORY/artifact.zip 

workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      - nexus:
          requires:
            - build
            
