version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
     
      - run:
          name: Build 
          command: CI=false npm run build
     
                  
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN
              
 

workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      
            
