version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Build the project
          command: CI=false npm run build
       
           
                  
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN
         
  docker_build_and_push:     
    docker:
      - image: circleci/node:16    
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/hotstar-app .
              
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD 
          
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/hotstar-app
      
  trivy_image_scanning:    
    docker:
      - image: circleci/node:16    
    steps:
      - checkout  
      - run:
          name: Install Trivy
          command: |
            wget https://github.com/aquasecurity/trivy/releases/download/v0.32.1/trivy_0.32.1_Linux-64bit.deb
            sudo dpkg -i trivy_0.32.1_Linux-64bit.deb
      - run:
          name: Scan Docker image with Trivy
          command: |
            trivy image $DOCKERHUB_USERNAME/hotstar-app > trivy_scan.txt
  
  
  
workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      - docker_build_and_push: 
          requires:
            - sonarQube
      - trivy_image_scanning:
          requires:          
            - docker_build_and_push            
