version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Build the project
          command: CI=false npm run build
      
      # Store the build artifacts
      - store_artifacts:
          path: dist/artifacts
          destination: artifacts    
      
      # Install Nexus CLI
      - run:
          name: Install Nexus CLI
          command: |
            curl -O https://download.sonatype.com/nexus/clm/scanner/cli/nexus-iq-cli-1.106.0-02.jar
      
                  
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN
         
    # Upload the artifact to Nexus
  upload_to_nexus:  
      - run:
          name: Upload to Nexus
          command: |
            java -jar nexus-iq-cli-1.106.0-02.jar upload \
              --repository=$NEXUS_URL/repository/$NEXUS_REPOSITORY/ \
              --dir="dist/artifacts" \
              --artifact="bundle.js" \
              --username=$NEXUS_USERNAME \
              --password=$NEXUS_PASSWORD \
              --url=$NEXUS_URL         
 
  # upload_to_nexus:
  #   docker:
  #     - image: sonatype/nexus-cli:latest
  #   steps:
  #     - checkout
           
  #     # Upload the artifact to Nexus
  #     - run:
  #         name: Upload to Nexus
  #         command: |
  #           java -jar nexus-iq-cli-1.106.0-02.jar upload \
  #             --repository=$NEXUS_URL/repository/$NEXUS_REPOSITORY/ \
  #             --dir="dist/artifacts" \
  #             --artifact="bundle.js" \
  #             --username=$NEXUS_USERNAME \
  #             --password=$NEXUS_PASSWORD \
  #             --url=$NEXUS_URL           
    
  
workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      - upload_to_nexus: 
          requires:
            - sonarQube
            
