version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          command: npx update-browserslist-db@latest 
      - run:
          name: Build
          command: CI=false npm run build
      
  sonarQube:    
    docker:
      - image: newtmitch/sonar-scanner:latest
    steps:
      - checkout  
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://54.158.21.154:9000 \
              -Dsonar.token=sqp_d84ae14dc3f4c100536493965c2fcc085fc1317a
              -Dsonar.login=$SONAR_TOKEN



            
