version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          command: npx update-browserslist-db@latest 
      - run:
          name: Build
          command: CI=false npm run build
      
  sonarQube:
    executor: node-executor
    docker:
      - image: newtmitch/sonar-scanner:latest 
    steps:
      - checkout
      - run:
         name: Download SonarScanner
         command: |
           curl -L -o sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
           unzip sonar-scanner-cli.zip
           export PATH="$PWD/sonar-scanner-4.6.2.2472-linux/bin:$PATH"
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://54.158.21.154:9000 \
              -Dsonar.token=sqp_d84ae14dc3f4c100536493965c2fcc085fc1317a
              -Dsonar.login=$SONAR_TOKEN


workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
            
