version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:16
     
jobs:
  build:
    executor: node-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      
      - run:
          name: Build the project
          command: CI=false npm run build
      
           
                  
  sonarQube:
    executor: node-executor
    docker:
      - image: sonarsource/sonar-scanner-cli:latest
    steps:
      - checkout
      
      - run:
          name: Run SonarQube Analysis
          command: |
            sonar-scanner \
              -Dsonar.projectKey=circle-ci \
              -Dsonar.sources=. \
              -Dsonar.host.url=$SONAR_HOST_URL \
              -Dsonar.token=$SONAR_TOKEN
         
  docker build and push:
    docker:
      - image: circleci/node:16   
     
    steps:
      - checkout
      - run:
         name: Build Docker Image
         command: docker build -t $DOCKERHUB_USERNAME/hotstar-app .
               
      - run:
          name: Login to Docker Hub
          command: docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
         
      - run:
          name: Push Docker Image
          command: docker push $DOCKERHUB_USERNAME/hotstar-app
    
  
workflows:
  version: 2.1
  build_and_analyze:
    jobs:
      - build
      - sonarQube:
          requires:
            - build
      - docker build and push: 
          requires:
            - sonarQube
            
